import 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js'
import 'https://cdn.jsdelivr.net/npm/bs-stepper/dist/js/bs-stepper.min.js'
// import './assets/js/select2'
// import 'https://code.jquery.com/jquery-3.7.0.js'
import 'https://unpkg.com/leaflet/dist/leaflet.js'
import 'https://unpkg.com/vue2-leaflet'
import 'https://unpkg.com/vue@3'
import 'https://unpkg.com/@hcaptcha/vue3-hcaptcha'
